<?php
define("API_KEY",'ap9UT2lMIKM-CwiuCKGWE6WT9jPyPatZrepFEbzW1E');
define("TEXTLOCAL_USERNAME",'vinoth@rigpa.in');
define("TEXTLOCAL_PASSWORD",'vino15Raj@');
define("DB_HOST","localhost");
define("DB_USERNAME","root");
define("DB_PASSWORD","amigo2020");
define("DB_NAME","heera_cars");
?>